# Generated by Django 2.0 on 2018-02-24 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsid', models.IntegerField(unique=True)),
                ('title', models.CharField(help_text='enter title for dataset', max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_filename', models.ImageField(null=True, upload_to='datasets/thumbnails/')),
                ('label_jsonfile', models.FileField(null=True, upload_to='datasets/labeljson/')),
            ],
        ),
        migrations.CreateModel(
            name='recent_activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('access_datetime', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='save_progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('dsid', models.IntegerField()),
                ('savefile', models.FileField(upload_to='saves')),
            ],
        ),
    ]
